apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reportportal-beta
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hlebkanonik/kubernetes-argocd
    targetRevision: HEAD
    path: reportportal
    helm:
      valueFiles:
        - ../argocd-apps/values/values-beta.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: beta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true